"""
EnglishAgent — English learning assistant agent for LearnForge.

This agent is invoked by the orchestrator when `requested_skill="english_chat"`.
It provides:
1. English chat context retrieval (word details, study history from EduMem0)
2. Word recommendation based on mastery
3. Quiz result sync to EduMem0

The actual LLM response is generated by Hermes runtime via the `english_chat` plan.
This module provides supporting services that enrich the Hermes prompt context.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)


class EnglishAgent:
    """Supporting services for English learning in LearnForge.

    The orchestrator's `english_chat` plan routes through Hermes for LLM generation.
    This class provides context enrichment and post-processing services.
    """

    def __init__(self, student_id: str):
        self.student_id = student_id

    # ── Context Retrieval ─────────────────────────────────────

    async def get_english_context(self, message: str) -> dict[str, Any]:
        """Retrieve English learning context for the Hermes prompt.

        Returns:
            Dictionary with word details, mastery info, and study history.
        """
        context: dict[str, Any] = {}

        # Extract word from message (simple heuristic)
        word = self._extract_word_from_message(message)
        if word:
            try:
                from app.english_word_service import get_word_detail
                detail = await get_word_detail(self.student_id, word)
                context["word_detail"] = detail
            except Exception as e:
                logger.debug(f"Word detail lookup failed for '{word}': {e}")

            try:
                from app.english_word_service import get_fission_graph
                fission = await get_fission_graph(self.student_id, word, depth=1)
                context["fission_graph"] = {
                    "synonyms": [n.get("label", n.get("id", "")) for n in fission.get("nodes", []) if n.get("type") == "synonym"][:8],
                    "antonyms": [n.get("label", n.get("id", "")) for n in fission.get("nodes", []) if n.get("type") == "antonym"][:8],
                    "derivatives": [n.get("label", n.get("id", "")) for n in fission.get("nodes", []) if n.get("type") == "derivative"][:8],
                }
            except Exception as e:
                logger.debug(f"Fission graph lookup failed for '{word}': {e}")

        # Get mastery info from EduMem0
        try:
            from app.edumem0.client import EduMem0Client
            mem0 = EduMem0Client()
            memories = mem0.search_memories(
                student_id=self.student_id,
                tags=["english"],
                limit=10,
            )
            context["english_memories"] = memories
        except Exception as e:
            logger.debug(f"EduMem0 lookup failed: {e}")

        return context

    # ── Quiz Result Sync ──────────────────────────────────────

    async def sync_quiz_result(
        self,
        word: str,
        quiz_type: str,
        score: float,
        answers: list[dict[str, Any]],
    ) -> None:
        """Sync quiz results to EduMem0.

        Records:
        - mastery memory: word mastery score
        - misconception memory: if score < 60
        """
        try:
            from app.edumem0.client import EduMem0Client
            from app.schemas.app_protocol import EduMemoryItem
            mem0 = EduMem0Client()
            mastery = float(score) / 100.0

            # Record mastery
            mem0.add(EduMemoryItem(
                student_id=self.student_id,
                memory_type="mastery",
                content=f"单词 {word} 掌握度 {mastery:.0%}",
                structured_payload={
                    "subject": "english",
                    "topic": word,
                    "score": mastery,
                    "quiz_type": quiz_type,
                },
                confidence=mastery,
                evidence_type="quiz_result",
                tags=["english", "vocabulary", "quiz"],
            ))

            # Record misconception if low score
            if score < 60:
                mem0.add(EduMemoryItem(
                    student_id=self.student_id,
                    memory_type="misconception",
                    content=f"单词 {word} 掌握薄弱，需要复习（测验得分 {score}）",
                    structured_payload={
                        "subject": "english",
                        "topic": word,
                        "score": score,
                        "quiz_type": quiz_type,
                    },
                    confidence=1.0 - mastery,
                    evidence_type="quiz_result",
                    tags=["english", "vocabulary", "weak"],
                ))

            logger.info(f"Synced quiz result for '{word}': score={score}")
        except Exception as e:
            logger.warning(f"Failed to sync quiz result to EduMem0: {e}")

    # ── Word Recommendation ───────────────────────────────────

    async def recommend_words(self, count: int = 10) -> list[dict[str, Any]]:
        """Recommend words based on student's mastery and weak points.

        Returns list of word entries with reason.
        """
        recommendations: list[dict[str, Any]] = []

        try:
            from app.edumem0.client import EduMem0Client
            mem0 = EduMem0Client()

            # Get weak words from misconceptions
            weak_memories = mem0.search_memories(
                student_id=self.student_id,
                memory_types=["misconception"],
                tags=["english"],
                limit=20,
            )

            for mem in weak_memories[:count]:
                word = mem.get("structured_payload", {}).get("topic", "")
                if word:
                    recommendations.append({
                        "word": word,
                        "reason": "之前测验得分较低，建议复习",
                        "priority": "high",
                    })
        except Exception as e:
            logger.debug(f"Word recommendation failed: {e}")

        # Fill remaining slots with random words from the word service
        if len(recommendations) < count:
            try:
                from app.english_word_service import get_word_list
                remaining = count - len(recommendations)
                result = await get_word_list(self.student_id, limit=remaining)
                for w in result.get("words", []):
                    recommendations.append({
                        "word": w.get("word", ""),
                        "reason": "新单词学习",
                        "priority": "normal",
                    })
            except Exception as e:
                logger.debug(f"Random word fill failed: {e}")

        return recommendations[:count]

    # ── Helpers ───────────────────────────────────────────────

    @staticmethod
    def _extract_word_from_message(message: str) -> str | None:
        """Extract an English word from the message text.

        Simple heuristic: look for patterns like:
        - "当前单词: word"
        - "关于 xxx 的问题"
        - Standalone English word
        """
        import re

        # Pattern: [英语学习] 当前单词: "word"
        match = re.search(r'当前单词[:\s]*["\']?(\w+)["\']?', message)
        if match:
            return match.group(1).lower()

        # Pattern: standalone English word (4+ letters, surrounded by non-word chars)
        match = re.search(r'\b([a-zA-Z]{4,})\b', message)
        if match:
            word = match.group(1).lower()
            # Skip common non-word matches
            if word not in {"英语学习", "about", "what", "how", "this", "that", "with", "from", "have", "they", "were", "been", "will", "would", "could"}:
                return word

        return None
